### ISSUE TITLE
Release v0.2.1

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/protobuf-specs#130]
Full release instructions are at: [RELEASE.md](/sigstore/protobuf-specs/blob/main/RELEASE.md)

## Pre Release
- [x] Check mediatype version of [Bundle](/sigstore/protobuf-specs/blob/main/protos/sigstore_bundle.proto), updating for major/minor releases
- [x] Check mediatype version of [TrustedRoot](/sigstore/protobuf-specs/blob/main/protos/sigstore_trustroot.proto), updating for major/minor releases
- [x] Update [CHANGELOG](/sigstore/protobuf-specs/blob/main/CHANGELOG.md)
- [x] Update [pyproject.toml](/sigstore/protobuf-specs/blob/main/gen/pb-python/pyproject.toml) so the `version` matches the targeted release
- [x] Update [package.json](/sigstore/protobuf-specs/blob/main/gen/pb-typescript/package.json) so the `version` matches the targeted release
- [x] Update [version.rb](/sigstore/protobuf-specs/blob/main/gen/pb-ruby/lib/sigstore_protobuf_specs/version.rb) so the `version` matches the targeted release
- [x] Update [Cargo.toml](/sigstore/protobuf-specs/blob/main/gen/pb-rust/Cargo.toml) so the `version` matches the targeted release

## Tag Release
- [x] `v<version>`
- [x] `release/java/v<version>`
- [x] `release/python/v<version>`
- [x] `release/ruby/v<version>`
- [x] `release/rust/v<version>`
- [x] `release/typescript/v<version>`
- [x] `release/jsonschema/v<version>`

## Publish Release
- [x] Java to Maven Central

## Verify Releases Published
- [x] [Java](https://central.sonatype.com/artifact/dev.sigstore/protobuf-specs/)
- [x] [Python](https://pypi.org/project/sigstore-protobuf-specs/)
- [x] [Ruby](https://rubygems.org/gems/sigstore_protobuf_specs)
- [x] [Rust](https://crates.io/crates/sigstore_protobuf_specs)
- [x] [Typescript](https://www.npmjs.com/package/@sigstore/protobuf-specs)

**Comment by haydentherapper** [comment]
@loosebazooka Can you sign and publish the Java release?

I noticed the jar is built and published as a draft release - https://github.com/sigstore/protobuf-specs/releases/tag/untagged-e53bdc03b1c9bbd27638. Could we automate signing by having the workflow sign the release with Cosign? If we need a pgp sig too, we could add that as a secret to the repo.

**Comment by loosebazooka** [comment]
I think we can automate releases too potentially if we create a separate group for `protobuf-specs-releaser@sigstore.dev` and add its credentials (might require a button press somewhere but I'm not sure)
