### ISSUE TITLE
How could the current protobuf spec model multiple bundle types ?

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/protobuf-specs#14]
**Question**

By looking at the current protobuf specification, I could identify how the spec reuses the current bundle format relying on Rekor entry logs, and additional fields (verification materials, ...) that aren't included today in the cosign bundle. 
However I am wondering how the current spec could model scenarios where Rekor is not in use. For instance, https://github.com/sigstore/cosign/issues/2331 proposes the usage of a Timestamp authority as an alternative guarantee for cosign signing/verification. To support this use case, the current protobuf spec will need additional fields in the TimestampVerificationData, and ignore other fields as well as the tlog entry data. 

Wouldn't it make the spec handier to have a Sigstore Bundle as an interface, and two or more types of Bundles such as RekorBundle or TimestampedBundle in the current spec definition ? These two types could model the aforementioned use case, and extend it to future verification mechanisms.

Any thoughts ? 
I hope I am not missing any previous discussion done during the creation of this spec.

@kommendorkapten @haydentherapper or others

**Comment by haydentherapper** [comment]
> Timestamp authority as an alternative guarantee for cosign signing/verification. To support this use case, the current protobuf spec will need additional fields in the TimestampVerificationData, and ignore other fields as well as the tlog entry data

I think this issue is specific to timestamping. In my opinion, this is misusing timestamping. There shouldn't be two bundle formats, because timestamping only provides a countersignature over an artifact signature, it doesn't provide auditability and signature transparency.

More generally, I think we should have a single bundle format, and it's up to clients on what to read as part of verification. If a client doesn't need transparency logs for some reason, then they can ignore that part of the bundle. I would really want to avoid multiple bundle formats, that's going to make client logic more complex.

**Comment by haydentherapper** [comment]
cc @znewman01

**Comment by haydentherapper** [comment]
Concretely, if the tlog isn't populated, then the bundle simply shouldn't populate [this field](https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_bundle.proto#L56). Clients should have verification policies that expect or don't expect transparency log entries.

**Comment by znewman01** [comment]
> More generally, I think we should have a single bundle format, and it's up to clients on what to read as part of verification. If a client doesn't need transparency logs for some reason, then they can ignore that part of the bundle. I would really want to avoid multiple bundle formats, that's going to make client logic more complex.

I agree. Your client should have some set of default verification options (which we'll prescribe as part of a client specification), like "require membership in Rekor (online) AND require a TSA signature". Then, in specific circumstances, you can override that default behavior.

I don't see why that's incompatible with the bundle spec as written, though.

**Comment by kommendorkapten** [comment]
Will only echo what @haydentherapper and @znewman01 already commented. The bundle is intended to be flexible to cover both many scenarios, such as only Rekor/tlog, signed timestamps and combinations of them, including some thresholds (i.e require the signature to be put on _X_  different Rekor instances). 
It all comes down to the verification policy on what fields to require. Both Rekor entries and signed timestamps are optional, as they are arrays (`repeated`), and an empty array is valid.
This is not very well specified yet, but as @znewman01 we are working on specifying this in the client specification.

**Comment by hectorj2f** [comment]
Thanks for the feedback and the detailed explanation. It sounds like there is a strong consensus on keeping a single bundle format for simplicity purposes. I was thinking of scenarios where the future complexity of this verification policy could be easily managed by a sigstore bundle with multiple nested bundle types.

Closing this issue then!
