### ISSUE TITLE
Add a registry of supported signature suites/hash algorithms

### ISSUE THREAD

**Issue by woodruffw** [sigstore/protobuf-specs#189]
Opening as a tracking issue; CCing @tetsuo-cpp and @ret2libc.

From initial discussion, `protobuf-specs` is probably the right place for this registry to live. It should probably be both a Markdown file and a `.proto` (containing enums/string constants for the cipher suite names, maybe?)

Blocked on completion of the relevant parts of the [Configurable Crypto Algorithms document](https://docs.google.com/document/d/18vTKFvTQdRt3OGz6Qd1xf04o-hugRYSup-1EAOWn7MQ/edit?usp=sharing).

**Comment by woodruffw** [comment]
Some relevant discussion items: 

* How "detailed" should the protobuf version of the registry be? In other words: should it list things like expected purposes (signing only, verifying only, both), or just be a "bare" list of every algorithm and suite that a Sigstore client might reasonably need to support?

**Comment by tetsuo-cpp** [comment]
This is addressed in #194, we can close this now.
