### ISSUE TITLE
Should we specify a key fingerprint algorithm for public key hint?

### ISSUE THREAD

**Issue by codysoyland** [sigstore/protobuf-specs#19]
**Question**

The public key "hint" in https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_common.proto#L73-L83 leaves the format of the key unspecified. What if we agree on a [standard fingerprinting algorithm such as this](https://pkg.go.dev/golang.org/x/crypto/ssh#FingerprintSHA256), which was extracted from OpenSSH?

This could simplify the verifier, as you would just need to configure it with a set of trusted public keys, and the hints/fingerprints would be derived automatically.

**Comment by znewman01** [comment]
I want to learn from the experience of TUF here. They started with a super-opinionated key ID format, then [later generalized it](https://github.com/theupdateframework/taps/blob/master/tap12.md) (some motivations in that doc). We're also following the lead of in-toto, which does the same thing.

My thinking is that key IDs are really an external concern to Sigstore—more a property of the application than the infrastructure. You might want semantically meaningful key IDs—I think we should support that.

IMO this won't make verifier shouldn't be terribly complex—a dict from key ID to public key should do it.

So I'm weakly -1 here.

**Comment by kommendorkapten** [comment]
I'm with @znewman01, I don't think this is Sigstore's business to define a key identificationschema. The same reasoning is true for DSSE envelope, which we pretty much copied the concept from. The clients may chose to use fingerprints, or simply ignoring the field totally and _always_ provide given key. 

As the hint is unauthenticated, the client must be in total control of how to deal with the value specified. If there was some semantics enforced by the bundle, some attacks could possibly open up where the attacker can change the key to use.

**Comment by codysoyland** [comment]
Makes sense, thanks for your input, @znewman01 and @kommendorkapten!
