### ISSUE TITLE
Clarify naming/types around verification bundle members?

### ISSUE THREAD

**Issue by woodruffw** [sigstore/protobuf-specs#30]
Similar to #29 -- I'm doing some reading through the protobufs now that we're getting close to integrating them into `sigstore-python`, and I wanted to check my understanding of a few things 🙂 

Here's the bundle as it's currently defined:

```protobuf
message Bundle {
        // MUST be application/vnd.dev.sigstore.bundle+json;version=0.1
        // when encoded as JSON.
        string media_type = 1;
        VerificationData verification_data = 2;
        dev.sigstore.common.v1.VerificationMaterial verification_material = 3;
        oneof content {
                dev.sigstore.common.v1.MessageSignature message_signature = 4;
                // A DSSE envelope can contain arbitrary payloads.
                // Verifiers must verify that the payload type is a
                // supported and expected type. This is part of the DSSE
                // protocol which is defined here https://github.com/secure-systems-lab/dsse/blob/master/protocol.md
                io.intoto.Envelope dsse_envelope = 5;
        }
        // Reserved for future additions of artifact types.
        reserved 6 to 50;
}
```

There are a couple members here that I currently find a little confusing (although it's very possible I don't understand them, and understanding them will resolve my confusion!):

* `VerificationData` is a pretty generic type name, and my first assumption was that it's a wrapper type for the input that was signed for. But it's actually a wrapper for a list of transparency log entries, plus materials for timestamp verification.
  * Proposal: either rename this to something like `ExtendedVerificationMaterials` (emphasizing that it's additional materials that can be used to verify additional properties), or maybe decompose it directly into the body of the `Bundle`?
* `MessageSignature` contains two parts: both a hash over the input, *and* a signature over the input. I found this a little confusing originally, since the two are conceptually separate (and it's not clear what role the hash plays in the bundle, since it can just be computed from the input being verified).
  * Proposal: either remove `MessageSignature.message_digest`, or decompose it into the surrounding `Bundle`? If we do the latter, we need to emphasize that checking the hash against the input's computed hash becomes important -- otherwise we might end up in another "confused metadata" circumstance where the user "verifies" a bundle without actually pinning it to the input they're verifying.
* `HashOutput` is a type that contains basically this tuple: `(hash-type, digest)`. However, my understanding of its use (per the CT RFC) is that the only valid hashing algorithm is SHA256 (despite SHA512 being defined). Am I missing a use case where we need this field to be generic over multiple hashing algorithms?

**Comment by znewman01** [comment]
CC @kommendorkapten 

> VerificationData is a pretty generic type name, and my first assumption was that it's a wrapper type for the input that was signed for. But it's actually a wrapper for a list of transparency log entries, plus materials for timestamp verification.
> * Proposal: either rename this to something like ExtendedVerificationMaterials (emphasizing that it's additional materials that can be used to verify additional properties), or maybe decompose it directly into the body of the Bundle?

Either of these SGTM

> MessageSignature contains two parts: both a hash over the input, and a signature over the input. I found this a little confusing originally, since the two are conceptually separate (and it's not clear what role the hash plays in the bundle, since it can just be computed from the input being verified).
> * Proposal: either remove MessageSignature.message_digest, or decompose it into the surrounding Bundle? If we do the latter, we need to emphasize that checking the hash against the input's computed hash becomes important -- otherwise we might end up in another "confused metadata" circumstance where the user "verifies" a bundle without actually pinning it to the input they're verifying.

This is an important concern. The point of the digest is that it "*can* be used to identify the artifact" (emphasis mine). So for instances where you might not have the artifact in hand yet (e.g., aren't downloading it from a content-addressable store until after it's verified.

I'd be okay with omitting this until a concrete use case comes up.

> HashOutput is a type that contains basically this tuple: (hash-type, digest). However, my understanding of its use (per the CT RFC) is that the only valid hashing algorithm is SHA256 (despite SHA512 being defined). Am I missing a use case where we need this field to be generic over multiple hashing algorithms?

This is more for the sake of completeness than anything. I could be persuaded that this is unnecessary "agility" that could bite us later.

*However*, I would like to specify the algorithm used *somewhere*. Maybe just hardcoded in the clients is okay?

**Comment by woodruffw** [comment]
> The point of the digest is that it "_can_ be used to identify the artifact" (emphasis mine). So for instances where you might not have the artifact in hand yet (e.g., aren't downloading it from a content-addressable store until after it's verified.

I hadn't considered that use case; that makes sense!

IMO in that case it probably makes sense to decompose it into the `Bundle`, and emphasize that the verifier is responsible for confirming that the actually retrieved content has a matching digest.

**Comment by kommendorkapten** [comment]
> Proposal: either rename this to something like ExtendedVerificationMaterials

That sounds reasonable. 

> IMO in that case it probably makes sense to decompose it into the Bundle, and emphasize that the verifier is responsible for confirming that the actually retrieved content has a matching digest.

I would think it should stay as is, but agree that we could emphasize that the verifier is responsible for confirming this. It's documented in the _suggested_ verification steps in the [client spec](https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit#heading=h.ybfrssxnyylb).

My reasoning on why it should stay in the `content` is that this is the main construct where the bundle is associated via an artifact and it's signature. Currently there are only two options (there are plans to extend this to capture more methods, e.g. the different kinds supported by Rekor). The two options are today:
* DSSE. A DSSE envelope captures both the content, content type and the signature in a single document. I.e the bundle _embeds_ artifact.
* "BLOB". The artifact is delivered via other means than the bundle. So the `message_siganture` here is used to identify the artifact (via the `message_digest`) _and_ capture the signature of the BLOB.

If we move out the `MessageSignature` from the `content` I think it would be more difficult to understand the bundle, and we could possibly end up with conflicting data in the bundle (e.g. the `MessageSignature` is not at all related to the artifact in the DSSE envelope). 

This probably deserves a better explanation, and as soon as we get the client spec in a decent shape we should reference that for the verification step. As this is still very early on, there are of course a bunch of missing documentation :)

**Comment by woodruffw** [comment]
Circling back here: I'll submit a PR for the `VerificationData` to `ExtendedVerificationMaterials` rename. 

> I would think it should stay as is, but agree that we could emphasize that the verifier is responsible for confirming this. It's documented in the _suggested_ verification steps in the [client spec](https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit#heading=h.ybfrssxnyylb).

SGTM! What do you think about making this a mandatory verification step? IMO it doesn't add a significant burden during verification, and eliminates the potential failure mode where a user thinks they don't need to check the digest but actually do.

> However, I would like to specify the algorithm used somewhere. Maybe just hardcoded in the clients is okay?

I'm personally good with this approach: `sigstore-python` hardcodes it already, and the potential agility here isn't exercisable anyways (since the CT spec forbids it anyways).

**Comment by kommendorkapten** [comment]
>  > However, I would like to specify the algorithm used somewhere. Maybe just hardcoded in the clients is okay?
> 
> I'm personally good with this approach: sigstore-python hardcodes it already, and the potential agility here isn't. exercisable anyways (since the CT spec forbids it anyways).

With the concept of a trust root (still WIP-ish), we have a way to capture both hash algorithm and signature algorithm: https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_trustroot.proto#L31

The struct has been discussed a bit and I would say is pretty mature, but the client considerations and methods of working with them are still WIP, but my hope is that we can have it in the client spec before EOY.

**Comment by kommendorkapten** [comment]
> My understanding of Sigstore certs is that domain names aren't allowed in SANs, and that the only currently valid SAN types are:
> 
> 1. Emails (e.g. for emails attested over an OIDC flow)
> 2. URIs (e.g. for GitHub workflows or other identities attested over OIDC)
> 3. "Usernames" (e.g. something like username!service)

Nice, the username principal was probably not there at the time the SAN type was created, so it should be added. I'll prepare a PR for that.  I can remove the DNS too if we think that it's confusing.

**Comment by kommendorkapten** [comment]
> Similarly, for `SubjectAlternativeName` itself: does it make sense to allow users to opt-out of regular expression matching? Clients like `sigstore-python` currently only support exact matches in their CLI, and for many identity emails that's the intuitive choice (e.g. you almost never want to match `.+@gmail\.com`). Then again, maybe that's not a concern at the message format layer (although I think it runs the risk of enabling users to unwittingly verify SANs because they match an unintended regexp).

This is a good one, how about we change this to a `oneof`, so it's clear if there is a regexp or a concrete value?

**Comment by kommendorkapten** [comment]
See https://github.com/sigstore/protobuf-specs/pull/37 for suggestions.

**Comment by woodruffw** [comment]
Both of those SGTM, thanks for the adjustments @kommendorkapten!
