### ISSUE TITLE
Should more messages/fields be marked as required?

### ISSUE THREAD

**Issue by woodruffw** [sigstore/protobuf-specs#40]
I'm a bit of a protobuf neophyte, so apologies if this is a silly or misguided question 🙂 

To my understanding, every field in a protobuf definition is optional by default (with the `optional` keyword really just being a way to mark that explicitly).

Given that many of our fields are absolutely required (such as the signature and inclusion proof), does it make sense to mark those as required at the wire level?

I see that Fulcio's protobuf definitions use the `(google.api.field_behavior) = REQUIRED` syntax, so is something similar to that appropriate here?

**Comment by haydentherapper** [comment]
https://google.aip.dev/203 - Required should be used in my opinion

**Comment by znewman01** [comment]
Can this be closed?

**Comment by woodruffw** [comment]
Yep!
