### ISSUE TITLE
Create and publish new java release v0.0.1

### ISSUE THREAD

**Issue by loosebazooka** [sigstore/protobuf-specs#45]
Just to get a release started (I understand the spec is not finalized), but we need something to work with for now

note: java release process requires `vN.N.N` (it's checked in the action). We should change that if we want to do a *.1a1 like python, but that's up to the repo owners.

A repo admin must (maybe @znewman01)
- [x] push a tag `release/java/v0.0.1`

Someone with sonatype[dev.sigstore] publish permissions must (probably @loosebazooka)
- [x] release to maven central

Detailed instructions at https://github.com/sigstore/protobuf-specs/blob/main/java/README.md

**Comment by znewman01** [comment]
https://github.com/sigstore/protobuf-specs/releases/tag/release%2Fjava%2Fv0.0.1

**Comment by loosebazooka** [comment]
hrmm... something weird happened with the release. like no "release" is present in the releases dir... did someone delete it?

**Comment by znewman01** [comment]
Are you looking for the draft release it created? https://github.com/sigstore/protobuf-specs/releases/tag/untagged-f5746bbc236b7a565d42

**Comment by loosebazooka** [comment]
(we already figured this out on slack), but it turns out I can't see draft releases because I'm not a project member

**Comment by loosebazooka** [comment]
well in an insane twist, it looks like the checksums stuff is unnecessary for the release path we take. I'll go clean that up. But the release is otherwise good to go.
