### ISSUE TITLE
Cut first release of the probuf messages.

### ISSUE THREAD

**Issue by kommendorkapten** [sigstore/protobuf-specs#47]
**Description**

I propose we cut the first release (i.e a tagged version) of the protobuf specs, as we have already seen some confusion of the state in this repository. My suggestion is that we leave the repository open for review until the week of January 9th 2023, then we discuss the state and see if we feel ready for the first release. If we need more time for review (holidays coming up) we can leave the repository open for one extra week.

cc: @haydentherapper @asraa @znewman01 @codysoyland @bdehamer @woodruffw

**Comment by znewman01** [comment]
That SGTM but let's clarify the stability expectations first.

We have been pushing "v0.0.1" test releases just to make sure that the per-language release processes are working (see #3)

**Comment by woodruffw** [comment]
SGTM as well! I'd be in favor of a cross-language `0.0.2` or `0.1.0` release so that we can get this into more hands for testing, while still maintaining the expectation that the messages here haven't fully stabilized.

**Comment by loosebazooka** [comment]
I'm releasing a v0.0.1 now of java to ensure my releases process are working and so we can start with integration into sigstore-java.

**Comment by kommendorkapten** [comment]
My expectation is that we actually stabilize the message and release the message format, especially for the `Bundle`. Language clients can be worked on, but once we start to produce/consume message we would like to stable messages that are versioned correctly. For sigstore-js we are already at a critical time now where are producing bundles, so any change to the bundle format is a bit painful.

The bundle format has gone through pretty thorough review, for four months now, so I would think we are ready to cut a release of the first bundle format (v0.1).

We know that there are things we want to adjust in the future, but we are depending on other services to update their formats too (e.g. Rekor SET v2 computation) but as there are no timelines we have to wait.

Other messages that I suspect will see some changes in the near future are messages related to trust root and verification, but to my knowledge no-one is yet using them so having them stable _now_ is not as important.

**Comment by loosebazooka** [comment]
Sure just open a bug for Java when ready to cut. I'll take care of it.

**Comment by asraa** [comment]
+1

> we know that there are future changes to happen, such as removing the canonicalized Rekor entry, but it's unsure when.

Agree, we shouldn't block on this.

**Comment by kommendorkapten** [comment]
During a call it just came up that the trusted root is expected to be serialized, and it doesn't have a media type like the bundle, so I created this PR: https://github.com/sigstore/protobuf-specs/pull/54

I would very much like to have that merged prior to the first release, WDYT?

**Comment by kommendorkapten** [comment]
Closing this, release tag pushed: https://github.com/sigstore/protobuf-specs/releases/tag/release%2Fv0.1.0

**Comment by woodruffw** [comment]
Awesome! FYI, you'll need to push separate language-specific tags to trigger releases for Java and Python, respectively 🙂

**Comment by kommendorkapten** [comment]
I'll need to push another tag, `v0.1.0`, as the current tag `release/v0.1.0` does not play nice with go 🤦 
I'll also push tags for Java and Python!

**Comment by kommendorkapten** [comment]
@woodruffw There was an error uploading to PyPI: https://github.com/sigstore/protobuf-specs/actions/runs/3900008634/jobs/6660205872 

Seems like it didn't pick up the correct tag?

Looking now, in `pyproject.toml`:
```
version = "0.0.1a2"
```

Do I need to update that file too? I can prepare a PR for that.

From the build step:
```
Successfully built sigstore-protobuf-specs-0.0.1a2.tar.gz and sigstore_protobuf_specs-0.0.1a2-py3-none-any.whl
```

```
Uploading sigstore_protobuf_specs-0.0.1a2-py3-none-any.whl
25l
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/24.6 kB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ [24](https://github.com/sigstore/protobuf-specs/actions/runs/3900008634/jobs/6660205872#step:6:25).6/24.6 kB • 00:00 • 71.1 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 kB • 00:00 • 71.1 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 kB • 00:00 • 71.1 MB/s
[25](https://github.com/sigstore/protobuf-specs/actions/runs/3900008634/jobs/6660205872#step:6:26)hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         File already exists. See https://pypi.org/help/#file-name-reuse for    
         more information.
```

**Comment by kommendorkapten** [comment]
@loosebazooka can you verify that the Java client was successfully built: https://github.com/sigstore/protobuf-specs/actions/runs/3900009220/jobs/6660245968

**Comment by kommendorkapten** [comment]
#57 is merged now, what would be the appropriate method to rerun the job. Delete the tag and push it again? I'm fine with that.

**Comment by znewman01** [comment]
Yeah I think that worked the last time I had this issue.

@kommendorkapten it kinda seems like we need a `RELEASE.md` document describing all these steps :)

**Comment by kommendorkapten** [comment]
@znewman01 Yes, it's on my todo-list :)

**Comment by kommendorkapten** [comment]
Python version successfully release now 🚢

**Comment by loosebazooka** [comment]
@znewman01 maybe you can turn it into a non-draft?

**Comment by haydentherapper** [comment]
Donw

**Comment by kommendorkapten** [comment]
Thanks @haydentherapper!

**Comment by kommendorkapten** [comment]
See https://github.com/sigstore/protobuf-specs/pull/58/files for added `RELEASE.md`
