### ISSUE TITLE
Certificate SAN Verification

### ISSUE THREAD

**Issue by bdehamer** [sigstore/protobuf-specs#55]
**Question**
In the `SubjectAlternativeNameType` [enum](https://github.com/sigstore/protobuf-specs/blob/a09e324bbc409628cef99a33e05fad2a5b4c47e5/protos/sigstore_common.proto#LL146C6-L146C32) there is a value named `SUBJECT_ALTERNATIVE_NAME_TYPE_UNSPECIFIED`. How should the certificates SAN extension be verified when this type is specified?

I understand how to retrieve/compare the extension values for `EMAIL` (assuming this maps to "rfc822Name [1]"), `URI` and `OTHER_NAME`, but I'm not sure what to do when the type is unspecified. Scan through the sequence of names and find anything that matches? Fail the verification regardless of value?

**Comment by haydentherapper** [comment]
I would say err out, unspecified is so we follow the protobuf standards from aip.dev

**Comment by kommendorkapten** [comment]
Yes, what @haydentherapper said, err out. 
The main reason for the `*_UNSPECIFIED` values in the enums is that the first value in the enum has the value 0, which in the default JSON serialization is omitted (as it's the default value). So by adding an unspecified value as the first will force a serialization that is explicit.

**Comment by bdehamer** [comment]
Makes sense. Thanks for the help @haydentherapper / @kommendorkapten
