### ISSUE TITLE
Ambiguity around `TransparencyLogEntry.canonicalized_body`

### ISSUE THREAD

**Issue by woodruffw** [sigstore/protobuf-specs#62]
I noticed this while trying to get `sigstore-python`'s WIP bundle generation verifying against `sigstore-js`: here's what the current `canonicalized_body` docs say:

```
        // The canonicalized Rekor entry body, used for SET verification. This
        // is the same as the body returned by Rekor. It's included here for
        // cases where the client cannot deterministically reconstruct the
        // bundle from the other fields. Clients MUST verify that the signature
        // referenced in the canonicalized_body matches the signature provided
        // in the bundle content.
```

I interpreted this as the _body_ of the response returned by Rekor, without the surrounding `apiVersion`, `kind`, etc. envelope. My reasoning there is that that's the canonicalized body that goes directly into SET verification, without any transformation, while including the envelope means that the user has to remove it and then potentially re-canonicalize. 

`sigstore-js` interprets it the other way: they include and expect the entire enveloped form.

IMO either of these interpretations is reasonable, but there probably needs to be exactly one 🙂

**Comment by haydentherapper** [comment]
Agreed we should describe this more clearly! We should imagine a user has never heard of the SET or knows about why we must canonicalize. It's meant to be the "body" that is returned from the Rekor API, and that along with the log index, log ID and time are signed over for the SET.

**Comment by woodruffw** [comment]
I can make a doc PR for this in a moment!

It turns out that my interpretation was the incorrect one -- I had confused the log entry body with the thing I call the "canonicalized entry" in `sigstore-python`, which is really the log entry body plus the other fields (like log ID, etc.) that are signed over for the SET.

**Comment by woodruffw** [comment]
Opened #63 with the doc changes.
