### ISSUE TITLE
Generate JSON Schema from Protobuf definitions and use it to enforce fields?

### ISSUE THREAD

**Issue by woodruffw** [sigstore/protobuf-specs#67]
Breakout from https://github.com/sigstore/protobuf-specs/pull/64#discussion_r1100287104: I think one possible solution to our "required" field woes is as follows:

1. Keep the current Protobuf definitions, and mark fields we expect/need as required;
2. Use a Protobuf to JSON Schema generator to generate a corresponding JSON Schema, including actual field enforcement (meaning that the generator will need to respect/handle the relevant annotations)
3. Use the generated JSON Schema to actually enforce the validity of JSON marshaled messages

This shouldn't be too difficult to do, and it looks like there's already some tooling out there that does it (<https://github.com/chrusty/protoc-gen-jsonschema>). 

OTOH, it adds _yet another_ layer of schematization, and only applies to JSON-marshaled messages. 

cc @znewman01

**Comment by kommendorkapten** [comment]
An alternative approach: the protobuf files are not expected to change that frequently. How about we hand code validate functions for each ecosystem, as part of the language bindings in this repo? 
Wire up conformance testing to the automation. It will be "expensive" upfront, but I think will simplify our lives down the road with much less complexity.

**Comment by znewman01** [comment]
Tbh I think we could get most of the benefits here by just making sure the conformance tests check for a proper media type, then each language can do it however they’d like.(I think all of the prior ideas are “better” but want to make sure we spend time on the most impactful issues :) )On Feb 9, 2023, at 4:15 AM, Fredrik Skogman ***@***.***> wrote:﻿
An alternative approach: the protobuf files are not expected to change that frequently. How about we hand code validate functions for each ecosystem, as part of the language bindings in this repo?
Wire up conformance testing to the automation. It will be "expensive" upfront, but I think will simplify our lives down the road with much less complexity.
