### ISSUE TITLE
Specify hash algorithm and signature algorithm for a transparency log.

### ISSUE THREAD

**Issue by kommendorkapten** [sigstore/protobuf-specs#7]
**Description**

The current bundle format does not capture the hash algorithms used by the log. This is called out in this comment https://github.com/sigstore/cosign/pull/2204#discussion_r996040149.

The information on hash and signature algorithm are now proposed to be part of the transparency log parameters used for verification per this PR: https://github.com/sigstore/protobuf-specs/pull/5/files#diff-b1f89b7fd3eb27b519380b092a2416f893a96fbba3f8c90cfa767e7687383ad4R31

My proposal is to omit this data from the bundle, and only capture it in the tlog parameters.

**Comment by znewman01** [comment]
Anything left to do here?

**Comment by kommendorkapten** [comment]
It's captured now in the `TransparencyLogInstance`: https://github.com/sigstore/protobuf-specs/blob/a09e324bbc409628cef99a33e05fad2a5b4c47e5/protos/sigstore_trustroot.proto#L31

So let's close this.
