### ISSUE TITLE
Extend the bundle format to capture PGP keys.

### ISSUE THREAD

**Issue by kommendorkapten** [sigstore/protobuf-specs#8]
**Description**

Originally captured in this comment: https://github.com/sigstore/protobuf-specs/pull/1/files#r1006690215

As PGP has a web of trust, a key unknown to the verifier can be trusted, as long as it's signed by another trusted key as described here: https://www.gnupg.org/gph/en/manual/x334.html. 

The bundle should be extended to allow for PGP keys to be stored, similar to how a public key identifier and X.509 certificate chain can be stored.

**Comment by znewman01** [comment]
I'm actually okay to close this I think. The PublicKeyIdentifier *could* refer to a GPG key, there's nothing stopping that at the moment.

I don't think we really want to enable web-of-trust use cases.

CC @bobcallaway for visibility
