### ISSUE TITLE
[Proposal] Require inclusion proofs

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/protobuf-specs#82]
As discussed in https://github.com/sigstore/rekor/issues/1566, I am proposing that inclusion proofs in bundles become mandatory. There are no server-side changes, as these are already returned.

Here's a table of the current support for inclusion proofs per client, and how they support verifying proofs (included SETs to be thorough).

|Client         |Proof included in bundle?                              |Verifying Proofs Offline|Verifying Proofs Online|Verifying SETs       |
|---------------|-------------------------------------------------------|------------------------|-----------------------|---------------------|
|sigstore-java  |Yes                                                    |Yes?                    |Yes?                   |Yes                  |
|sigstore-js    |[WIP](https://github.com/sigstore/sigstore-js/pull/578)|No                      |No                     |Yes                  |
|sigstore-python|Yes                                                    |Yes                     |Yes                    |Yes                  |
|cosign         |No, no bundle support                                  |Yes (not from bundle)   |Yes                    |Yes (not from bundle)|
|sigstore-rs    |No, no bundle support                                  |No                      |No                     |Yes?                 |

@bdehamer @woodruffw @loosebazooka @znewman01 Please let me know if anything is inaccurate or help fill in the question marks.

**Comment by woodruffw** [comment]
`sigstore-python` supports both online and offline proof verification, so I _think_ that should be a yes 🙂
