### ISSUE TITLE
Proposal: Include raw Rekor Bundle in TransparencyLogEntry

### ISSUE THREAD

**Issue by codysoyland** [sigstore/protobuf-specs#9]
**Description**

The bundle spec includes [transparency log entries](https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_rekor.proto#L96-L113). In earlier discussions and [the unmerged verification documentation](https://github.com/kommendorkapten/cosign/blob/bundle_verification/specs/dotsigstore_bundle/verify.md), I think we agreed that IF a log entry is provided in the bundle, we MUST perform a successful SET verification (inclusion promise).

The [SET verification](https://github.com/sigstore/cosign/blob/main/pkg/cosign/verify.go#L1061-L1077) requires 6 pieces of data:
- canonicalized Rekor entry
- integrated time
- log index
- log id
- Rekor's public key
- signature (known as the SET)

All of the above fields are included in the bundle except for the canonicalized Rekor entry. It was decided in the original proposal to reconstruct it from other data in the bundle, and by adding `KindVersion` to hint to the verifier which entry version to reconstruct. I believe this decision was made due to the fact that the intoto type would duplicate the DSSE in the bundle, producing a larger file size due to the redundant data.

Unfortunately, we still lack enough information to deterministically reproduce all Rekor entries. This was called out in the original proposal, but it was believed that we could reconstruct `hashedRekord` and `intoto` entries, which I understand to be the only supported entry types for the bundle. In fact, the intoto type still has an ambiguous field, the `hash` value which is calculated over the DSSE envelope. Rekor does not enforce any canonicalization of the DSSE used to produce the hash in the intoto v0.0.2 type, therefore, current intoto v0.0.2 entries cannot be verified without the raw bytes of the DSSE, which are not included in the bundle.

Additionally, it is a large burden to place on non-Go clients to reproduce the behavior of all the supported Rekor entry types, and I believe this will lead to verifiers that don't follow spec.

In my opinion, we should just capture the raw Rekor entry in the `TransparencyLogEntry`.

Alternatives:
-  We can just leave it as-is and require online verification for Rekor entries, but that kinda breaks the goal of offline verification of these bundles.
- We can use TSA countersignatures to verify the signature was produced while the certificate was valid, which offers much of the same level of authenticity

**Comment by codysoyland** [comment]
Just saw that Bob did acknowledge that the user-supplied hash in intoto v0.0.2 is a bug and should be fixed in v0.0.3: https://github.com/sigstore/rekor/issues/1162#issuecomment-1302245965

**Comment by kommendorkapten** [comment]
Another thing that @bdehamer found that will make it hard to reconstruct the Rekor entry: https://github.com/sigstore/rekor/issues/1170

**Comment by asraa** [comment]
Maybe this is a 2 step:

1.Capture the canoncalized rekor entry in the bundle. Tell clients to validate the signatures are equal to prove "matching bundle".
2. In Rekor v2, we may change this either by simplifying types OR by simplifying the SET content.
