### ISSUE TITLE
Maintain a CHANGELOG of protobuf changes between versions

### ISSUE THREAD

**Issue by woodruffw** [sigstore/protobuf-specs#91]
We're still pre-1.0, but I think this would be valuable going forwards: it'll be nice to have a concise index of the changes between versions, so that clients can quickly adapt their usage 🙂

**Comment by haydentherapper** [comment]
+1! Here's what I'd write up for 0.2, we can just copy this into a changelog if this works, and add a changelog step to release.md:

Breaking changes:
* Require inclusion proofs, make promises optional
* Mark most fields for Rekor as required
* Ruby: Change class name

Documentation:
* Clarify that `canonicalized_body` is optional as it can be constructed from other fields
* Clarify key ID is a digest over Subject Public Key ID (SPKI)
* Specify that certificate chain should not contain the root certificate, and should not include trusted intermediate certificates
* Clarify time range validity

Other:
* Add Rust support

**Comment by woodruffw** [comment]
Thanks for summarizing that! I can seed an initial CHANGELOG with that tonight or tomorrow.
