### ISSUE TITLE
Upload v0.2.0 to Maven Central 

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/protobuf-specs#92]
Tracking bug to make sure we follow through once I get permission or chat with someone who does. Release bundle is attached.

[release_java_v0.2.0.zip](https://github.com/sigstore/protobuf-specs/files/12034050/release_java_v0.2.0.zip)

**Comment by haydentherapper** [comment]
@loosebazooka Would you be able to upload this? This is the recently released 0.2 cut ([changelog](https://github.com/sigstore/protobuf-specs/blob/main/CHANGELOG.md#020), main changes were to require inclusion proofs and a few more rekor response fields). I don't have the credentials

**Comment by loosebazooka** [comment]
will do.

**Comment by loosebazooka** [comment]
FYI for anyone that comes upon this issue in the future -- the linked release bundle in the first comment is not what we upload. It's a single file in the generated release directory: https://github.com/sigstore/protobuf-specs/tree/main/java#releasing

**Comment by loosebazooka** [comment]
anyway, the release has been done, I'll close this once it starts showing up on maven central

**Comment by loosebazooka** [comment]
Also there's a release checklist bug template for tracking releases :D

**Comment by haydentherapper** [comment]
Ah, to confirm, it's just the JAR, not the zip?

**Comment by loosebazooka** [comment]
> Ah, to confirm, it's just the JAR, not the zip?
yeah `something-something-bundle.jar`, I'm not actually sure where this zip came from?

anyway, it's up on maven central now: https://repo1.maven.org/maven2/dev/sigstore/protobuf-specs/0.2.0/

**Comment by loosebazooka** [comment]
this issues can be closed (I do not have permissions)

**Comment by haydentherapper** [comment]
IIRC sign_and_bundle_release.sh produced something and I zipped it up, but I don't recall.
